# Generated by Django 4.1.2 on 2022-10-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('link', models.URLField(help_text='The url of the artist', max_length=350)),
                ('share', models.URLField(help_text='The share link of the artist', max_length=350)),
                ('picture', models.ImageField(default='images/artist/avatar-default.png', help_text='The url of the artist picture.', upload_to='images/artist/')),
                ('nb_album', models.IntegerField(help_text="The number of artist's albums")),
                ('nb_fan', models.IntegerField(help_text="The number of artist's fans")),
                ('radio', models.BooleanField(default=False, help_text='true if the artist has a smartradio', verbose_name='radio')),
                ('tracklist', models.URLField(help_text='API Link to the top of this artist', max_length=350)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
