# Generated by Django 4.1.2 on 2022-10-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='link',
            field=models.URLField(blank=True, help_text='The url of the artist', max_length=350),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nb_album',
            field=models.IntegerField(default=0, help_text="The number of artist's albums"),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nb_fan',
            field=models.IntegerField(default=0, help_text="The number of artist's fans"),
        ),
        migrations.AlterField(
            model_name='artist',
            name='share',
            field=models.URLField(blank=True, help_text='The share link of the artist', max_length=350),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tracklist',
            field=models.URLField(blank=True, help_text='API Link to the top of this artist', max_length=350),
        ),
    ]
