# Generated by Django 4.1.2 on 2022-10-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_nb_album_alter_artist_nb_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nb_album',
            field=models.IntegerField(help_text="The number of artist's albums", null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nb_fan',
            field=models.IntegerField(help_text="The number of artist's fans", null=True),
        ),
    ]
