# Generated by Django 4.1.2 on 2022-10-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterField(
            model_name='client',
            name='tracklist',
            field=models.URLField(blank=True, help_text='API Link to the flow of this user', max_length=350),
        ),
    ]
