# Generated by Django 4.1.2 on 2022-10-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('clients', '0003_alter_client_options_alter_client_tracklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, help_text="The user's country", null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.ForeignKey(blank=True, help_text="The user's gender", null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.gender'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lang',
            field=models.ForeignKey(blank=True, help_text="The user's lang", null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.language'),
        ),
    ]
